SourceCode/Controllers/ExamController.cs
using Aptitude.Data;
using Aptitude.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Identity;

namespace Aptitude.Controllers
{
    
    public class ExamController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        public ExamController(ApplicationDbContext context, SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> UserManager)
        {
            _context = context;
            _signInManager = signInManager;
            _userManager = UserManager;
        }
        public IActionResult CheckProfile()
        {
            HttpContext.Session.Clear();
            _signInManager.SignOutAsync();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Index()
        {
            var modelUser = _context.CV.SingleOrDefault(m => m.Email.Equals(User.Identity.Name));
            ViewBag.model = modelUser;
            var countGeneral = _context.Question.Where(l => l.DepartmentId == 1).ToList().Count;
            var countMath = _context.Question.Where(l => l.DepartmentId == 2).ToList().Count;
            var countComputer = _context.Question.Where(l => l.DepartmentId == 3).ToList().Count;
            if (countGeneral != 5 || countMath != 5 || countComputer != 5)
            {
                ViewBag.error = 1;
            }

            var isUser = User.IsInRole("Admin");
            if (isUser)
                ViewBag.Admin = "admin";
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("exam")))
                HttpContext.Session.SetString("exam", "1");

            var checkTest = _context.Exam.SingleOrDefault(c=>c.Id.Equals(modelUser.ExamId));
            var checkTest1 = _context.Exam.SingleOrDefault(c => c.Id.Equals(modelUser.ExamId+1));
            var checkTest2 = _context.Exam.SingleOrDefault(c => c.Id.Equals(modelUser.ExamId+2));// phai cho logout truoc roi moi login lai
            if (checkTest.Answer == "f" || checkTest1.Answer == "f" || checkTest2.Answer == "f")
            {
                ViewBag.checkTest = 0;
            }
            else 
            {
                ViewBag.checkTest = 1;
            }
            return View();
        }
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult GeneralExam()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("exam")))
            {
                return RedirectToAction("Homepage", "Home");
            }
            var ModelCV = _context.CV.SingleOrDefault(c => c.Email.Equals(User.Identity.Name));
            if (!HttpContext.Session.GetString("exam").Equals("1") || ModelCV.Status != 0)
            {
                return RedirectToAction("Index");
            }
            var listquestion = _context.Question.Where(q => q.Category == 1).Take(5);
            ViewBag.Result = "open";
            ViewBag.checking = 1;

            HttpContext.Session.SetString("exam", "2");
            return View(listquestion);
        }
        [HttpPost]
        public IActionResult GeneralExam(IFormCollection form, string submit)
        {
            string aswn1 = "";
            if (string.IsNullOrEmpty(form["answer1"]))
                aswn1 = "t+1";
            else
                aswn1 = form["answer1"];
            string aswn2 = "";
            if (string.IsNullOrEmpty(form["answer2"]))
                aswn2 = "t+1";
            else
                aswn2 = form["answer2"];
            string aswn3 = "";
            if (string.IsNullOrEmpty(form["answer3"]))
                aswn3 = "t+1";
            else
                aswn3 = form["answer3"];
            string aswn4 = "";
            if (string.IsNullOrEmpty(form["answer4"]))
                aswn4 = "t+1";
            else
                aswn4 = form["answer4"];
            string aswn5 = "";
            if (string.IsNullOrEmpty(form["answer5"]))
                aswn5 = "t+1";
            else
                aswn5 = form["answer5"];
            string FinalAnswer = aswn1 + "//" + aswn2 + "//" + aswn3 + "//" + aswn4 + "//" + aswn5;
            string[] array1 = aswn1.Split('+');
            string[] array2 = aswn2.Split('+');
            string[] array3 = aswn3.Split('+');
            string[] array4 = aswn4.Split('+');
            string[] array5 = aswn5.Split('+');

            var listquestion = _context.Question.ToList();

            //check answer
            int Point = 0;
            if (!String.IsNullOrEmpty(aswn1))
            {
                var question1 = listquestion.SingleOrDefault(l => l.Id.Equals(int.Parse(array1[1])));
                if(question1 == null)
                {
                    Point += 0;
                }
                else if (question1.FinalAnswer.Equals(array1[0]))
                {
                    Point += question1.Level;
                }
            }

            if (!String.IsNullOrEmpty(aswn2))
            {
                var question2 = listquestion.SingleOrDefault(l => l.Id.Equals(int.Parse(array2[1])));
                if (question2 == null)
                {
                    Point += 0;
                }
                else if (question2.FinalAnswer.Equals(array2[0]))
                {
                    Point += question2.Level;
                }
            }


            if (!String.IsNullOrEmpty(aswn3))
            {
                var question3 = listquestion.SingleOrDefault(l => l.Id.Equals(int.Parse(array3[1])));
                if (question3 == null)
                {
                    Point += 0;
                }
                else if (question3.FinalAnswer.Equals(array3[0]))
                {
                    Point += question3.Level;
                }
            }


            if (!String.IsNullOrEmpty(aswn4))
            {
                var question4 = listquestion.SingleOrDefault(l => l.Id.Equals(int.Parse(array4[1])));

                if (question4 == null)
                {
                    Point += 0;
                }
                else if (question4.FinalAnswer.Equals(array4[0]))
                {
                    Point += question4.Level;
                }
            }


            if (!String.IsNullOrEmpty(aswn5))
            {
                var question5 = listquestion.SingleOrDefault(l => l.Id.Equals(int.Parse(array5[1])));

                if (question5 == null)
                {
                    Point += 0;
                }
                else if (question5.FinalAnswer.Equals(array5[0]))
                {
                    Point += question5.Level;
                }
            }

            //save record
            var modelCV = _context.CV.SingleOrDefault(c => c.Email.Equals(User.Identity.Name));
            var general = _context.Exam.Find(modelCV.ExamId);
            general.Mark = Point;
            if (Point <= 50)
                general.Result = "Failed";
            else
                general.Result = "Passed";
            general.Date = DateTime.Now;
            general.Answer = FinalAnswer;

            _context.Exam.Update(general);
            _context.SaveChanges();
            //end save record
            ViewBag.Point = Point;
            ViewBag.Result = "done";
            ViewBag.checking = 2;
            HttpContext.Session.SetString("GeneralPoints", Point.ToString());
            return View(listquestion);
        }
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult MathExam()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("exam")))
            {
                return View("Homepage", "Home");
            }
            if (!HttpContext.Session.GetString("exam").Equals("2"))
            {
                return View("Index");
            }

            var listquestion = _context.Question.Where(q => q.Category == 2).Take(5);
            ViewBag.Result = "open";
            ViewBag.checking = 1;

            HttpContext.Session.SetString("exam", "3");

            return View(listquestion);
        }
        [HttpPost]
        public IActionResult MathExam(IFormCollection form, string submit)
        {
            string aswn1 = "";
            if (string.IsNullOrEmpty(form["answer1"]))
                aswn1 = "t+1";
            else
                aswn1 = form["answer1"];
            string aswn2 = "";
            if (string.IsNullOrEmpty(form["answer2"]))
                aswn2 = "t+1";
            else
                aswn2 = form["answer2"];
            string aswn3 = "";
            if (string.IsNullOrEmpty(form["answer3"]))
                aswn3 = "t+1";
            else
                aswn3 = form["answer3"];
            string aswn4 = "";
            if (string.IsNullOrEmpty(form["answer4"]))
                aswn4 = "t+1";
            else
                aswn4 = form["answer4"];
            string aswn5 = "";
            if (string.IsNullOrEmpty(form["answer5"]))
                aswn5 = "t+1";
            else
                aswn5 = form["answer5"];
            string FinalAnswer = aswn1 + "//" + aswn2 + "//" + aswn3 + "//" + aswn4 + "//" + aswn5;
            string[] array1 = aswn1.Split('+');
            string[] array2 = aswn2.Split('+');
            string[] array3 = aswn3.Split('+');
            string[] array4 = aswn4.Split('+');
            string[] array5 = aswn5.Split('+');

            var listquestion = _context.Question.ToList();

            //check answer
            int Point = 0;

SourceCode/Views/Shared/AdminLTE/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <partial name="AdminLTE/_Styles" />
    @RenderSection("CSS", required: false)
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <partial name="AdminLTE/_MainSidebar" />
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <section class="content">
                <!-- /.container-fluid -->
                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.0.5
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <partial name="AdminLTE/_Scripts" />
    @RenderSection("Scripts", required: false)
</body>

</html>

SourceCode/Views/Shared/AdminLTE/_MainSidebar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a asp-controller="Admin" asp-action="Index" class="brand-link">
        <img src="/Lte/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">DASHBOARD</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!--QUESTION-->
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-copy"></i>
                        <p>
                            Question
                            <i class=" right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <!--Question Create New-->
                        <li class="nav-item">
                            <a asp-action="Question_Create" asp-controller="Admin" class="nav-link">
                                <i class="fas fa-plus nav-icon"></i>
                                <p>Create New Question</p>
                            </a>
                        </li>
                        <!--List General Question-->
                        <li class="nav-item">
                            <a asp-action="Question_General" asp-controller="Admin" class="nav-link">
                                <i class="fas fa-list nav-icon"></i>
                                <p> General Question</p>
                            </a>
                        </li>
                        <!--List Math Question-->
                        <li class="nav-item">
                            <a asp-action="Question_Math" asp-controller="Admin" class="nav-link">
                                <i class="fas fa-list nav-icon"></i>
                                <p> Math Question</p>
                            </a>
                        </li>
                        <!--List Computer Technology Question-->
                        <li class="nav-item">
                            <a asp-action="Question_Computer" asp-controller="Admin" class="nav-link">
                                <i class="fas fa-list nav-icon"></i>
                                <p> Technology Question </p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!--DEPARTMENT-->
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Department
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <!--Question Create New-->
                        <li class="nav-item">
                            <a asp-action="Department_Create" asp-controller="Admin" class="nav-link">
                                <i class="fas fa-plus nav-icon"></i>
                                <p>Create New Department</p>
                            </a>
                        </li>
                        <!--List General Question-->
                        <li class="nav-item">
                            <a asp-action="Department_Index" asp-controller="Admin" class="nav-link">
                                <i class="fas fa-list nav-icon"></i>
                                <p>List Department</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!--ACCOUNT-->
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Account Management
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <!--Account Create New-->
                        <li class="nav-item">
                            <a asp-action="Create_User" asp-controller="Admin" class="nav-link">
                                <i class="fas fa-plus nav-icon"></i>
                                <p>Create New Account</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <!--Report-->
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-pager"></i>
                        <p>
                            Report
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <!--Exam-->
                        <li class="nav-item">
                            <a asp-action="ReportExam" asp-controller="Admin" class="nav-link">
                                <i class="fas fa-list nav-icon"></i>
                                <p>Exam</p>
                            </a>
                        </li>
                        <!--Question-->
                        <li class="nav-item">
                            <a asp-action="ReportQuestion" asp-controller="Admin" class="nav-link">
                                <i class="fas fa-list nav-icon"></i>
                                <p>Question</p>
                            </a>
                        </li>
                        <!--CV-->
                        <li class="nav-item">
                            <a asp-action="ReportCV" asp-controller="Admin" class="nav-link">
                                <i class="fas fa-list nav-icon"></i>
                                <p>CV</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!--Select question -->
                @*<li class="nav-item has-treeview">
        <a href="#" class="nav-link">
            <i class="nav-icon fas fa-copy"></i>
            <p>
                Select Question
                <i class=" right fas fa-angle-left"></i>
            </p>
        </a>
        <ul class="nav nav-treeview" style="display: none;">*@
                <!--List General Question-->
                @*<li class="nav-item">
            <a asp-action="SelectGeneral" asp-controller="Admin" class="nav-link">
                <i class="fas fa-list nav-icon"></i>
                <p>Select General Question</p>
            </a>
        </li>*@
                <!--List Math Question-->
                @*<li class="nav-item">
            <a asp-action="SelectMath" asp-controller="Admin" class="nav-link">
                <i class="fas fa-list nav-icon"></i>
                <p>Select Math Question</p>
            </a>
        </li>*@
                <!--List Computer Technology Question-->
                @*<li class="nav-item">
            <a asp-action="SelectComputer" asp-controller="Admin" class="nav-link">
                <i class="fas fa-list nav-icon"></i>
                <p>Select Technology Question </p>
            </a>
        </li>*@
                <!-- End select question -->
                <!--List General Question-->
                @*</ul>
        </li>*@
                <!-- end Select question -->
                <li class="nav-item has-treeview">
                    <a asp-action="Select" asp-controller="Exam" class="nav-link">
                        <i class="nav-icon fas fa-hand-point-right"></i>
                        <p>
                            Select
                            <i class="fas fa-check right"></i>
                        </p>
                    </a>
                </li>
                <!--DEPARTMENT-->
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-file-alt"></i>
                        <p>
                           Tested CV
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <!--Question Create New-->
                        <li class="nav-item">
                            <a asp-action="AllCV" asp-controller="Exam" class="nav-link">
                                <i class="fas fa-address-book nav-icon"></i>
                                <p>List of Tested CV</p>
                            </a>
                        </li>
                        <!--List General Question-->
                        <li class="nav-item">
                            <a asp-action="HR" asp-controller="Exam" class="nav-link">
                                <i class="fas fa-ambulance nav-icon"></i>
                                <p>HR</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!--Log Out-->
                <li class="nav-item has-treeview">
                    <a asp-action="LogOut" asp-controller="Exam" class="nav-link">
                        <i class="nav-icon fas fa-sign-out-alt"></i>
                        <p>
                            Log Out
                            <i class="fas fa-sign-out right"></i>
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

SourceCode/Views/Shared/AdminLTE/_Scripts.cshtml
<script src="~/Lte/plugins/jquery/jquery.min.js"></script>
<script src="~/Lte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/Lte/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/Lte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/Lte/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/Lte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>

<script src="~/Lte/plugins/jquery-ui/jquery-ui.min.js"></script>
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<script src="~/Lte/plugins/summernote/summernote-bs4.min.js"></script>
<script src="~/Lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<script src="~/Lte/dist/js/adminlte.js"></script>

SourceCode/Views/Shared/AdminLTE/_Styles.cshtml
<link href="~/Lte/plugins/fontawesome-free/css/all.min.css" rel="stylesheet"/>
<link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet"/>
<link href="~/Lte/dist/css/adminlte.min.css" rel="stylesheet"/>
<link href="~/Lte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css" rel="stylesheet"/>
<link href="~/Lte/plugins/summernote/summernote-bs4.css" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet"/>
<link href="~/Lte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="~/Lte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css" rel="stylesheet" />